apiVersion: v1
kind: Pod
metadata:
  name: temp-shell
  namespace: test-ananta
spec:
  containers:
  - name: shell
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-release-typesense-pvc
